version: '3.7'

networks:
  homefinances:

services:
  mysql:
    image: mysql:latest
    container_name: home-finances-mysql
    env_file: ./.env
    ports:
      - 3307:3306
    networks:
      - homefinances
    volumes:
      - /etc/docker/home-finances-db:/etc/mysql/conf.d
      - /home-finances-db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=homefinances
      - MYSQL_ROOT_HOST='%'
    restart: unless-stopped

  dev:
    depends_on:
      - mysql
    container_name: home-finances-dev
    env_file: ./.env
    ports:
      - 4002:4002
    build: ./
    environment:
      - DB_HOST=$DB_HOST
      - DB_USERNAME=$DB_USERNAME
      - DB_PASSWORD=$DB_PASSWORD
      - DB_DATABASE=$DB_DATABASE
      - DB_PORT=$DB_PORT
    networks:
      - homefinances
    restart: unless-stopped
