version: '3.7'

networks:
  homefinances:

services:
  mysql:
    image: mysql:latest
    container_name: home-finances-mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    networks:
      - homefinances
    stdin_open: true
    tty: true
    # volumes:
    #   - /etc/docker/home-finances-db:/etc/mysql/conf.d
    #   - /home-finances-db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=homefinances
      - MYSQL_ROOT_HOST='%'
    restart: unless-stopped
    volumes:
      - mysql-data:/var/lib/mysql

  dev:
    build: ./
    container_name: home-finances-backend
    depends_on:
      - mysql
    env_file: ./.env
    ports:
      - 4002:4002
    environment:
      - DB_HOST=$DB_HOST
      - DB_USERNAME=$DB_USERNAME
      - DB_PASSWORD=$DB_PASSWORD
      - DB_DATABASE=$DB_DATABASE
      - DB_PORT=$DB_PORT
    networks:
      - homefinances
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  mysql-data:
